name: Verify Assignments
on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    strategy:
      matrix:
        user: [marcprux]

    steps:
      - name: Configure 
        run: |
          echo "REPO=$(echo ${GITHUB_REPOSITORY} | cut -d / -f 2)" >> $GITHUB_ENV

      - name: Checkout 
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.user }}/${{ env.GHREPO }}
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Verify 
        run: |
          sh verify.sh
  
