name: Verify Assignments
on: 
  schedule:
    - cron: '30 17 * * *'
  workflow_dispatch:


jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    strategy:
      matrix:
        student: [marcprux, marcprux, marcprux]

    steps:
      - name: Configure Student Fork
        run: |
          echo "REPO=$(echo ${GITHUB_REPOSITORY} | cut -d / -f 2)" >> $GITHUB_ENV

      - name: Checkout Student Fork
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.student }}/${{ env.REPO }}
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Verify Student Fork
        run: |
          cd "${{ matrix.student }}"/
          sh ../verify.sh
  
